### ISSUE TITLE
First release date ?

### ISSUE THREAD

**Issue by Aetherall** [js-accounts/next#1]
Hi ! You are doing an amazing work !

Have you any thought to share about the release date ?

Can't wait to use the package in production

**Comment by davidyaha** [comment]
Hey @Aetherall!
As I wrote on https://github.com/js-accounts/accounts/issues/111, the js-accounts bundle of packages is already released.
This repository reflects the direction we would like to take as written by @pradel and myself, but we use this as reference for implementations done on the other repositories.

You (or anyone else dropping in here) can see the current status of implementing this in https://github.com/js-accounts/accounts/issues/107

**Comment by Aetherall** [comment]
Thanks @davidyaha !
